WIP: Initial FreeBSD port
3mdeb/fwupd pull request #6
Opened 2021-06-01 14:59 UTC by mkopec

This patch enables initial support for FreeBSD.

Currently it does not compile due to fwupd/fwupd#3307

2021-06-02 11:10 UTC, mkopec commented
This branch should now compile successfully. However, it requires efivar with https://github.com/rhboot/efivar/commit/4af5b56066b4af66ce8d968948bb2bf4f5a87c79 applied.

2021-06-04 14:31 UTC, Asiderr requested changes

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	while (efi_get_next_variable_name(&guid, &name)) {
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	if (efi_set_variable(guid, name, data, sz, attr) != 0) {
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid_to_delete);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&guid_to_delete, guid, sizeof(guid)) == 0) {
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +				rv = fu_efivar_delete(guids, name, error);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &test);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&test, guid, sizeof(test)) == 0) {
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &test);
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&test, guid, sizeof(test)) == 0) {
Please, add space after function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> + * Since: 1.5.1
Please change version tags.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> + * Copyright (C) 2021 Norbert Kamiński <norbert.kaminski@3mdeb.com>
Please, add yourself and Sergii

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +static gchar *
Please, add function description

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Please add space function name.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&test, guid, sizeof(test)) == 0) {
Brackets not needed.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (efi_get_variable_size (*guid, name, &size) < 0) {
Brackets not needed.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +				if (!rv) {
Brackets not needed.

2021-06-04 14:31 UTC, Asiderr commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&guid_to_delete, guid, sizeof(guid)) == 0) {
Avoid nested `if`s. Use reversed conditions e.g.:
```
if (memcmp(&guid_to_delete, guid, sizeof(guid)) != 0)
        continue;

if (!fu_common_fnmatch (name, name_glob))
        continue;

rv = fu_efivar_delete(guids, name, error);
if (!rv)
        break;
```

2021-06-04 14:34 UTC, Asiderr commented on libfwupdplugin/meson.build
> +if host_machine.system() == 'linux'
If freebsd - `fu-efivar-freebsd.c`, else `fu-efivar.c`. Windows also will use `fu-efivar.c`.

2021-06-07 07:11 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	while (efi_get_next_variable_name(&guid, &name)) {
Done.

2021-06-07 07:11 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	if (efi_set_variable(guid, name, data, sz, attr) != 0) {
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid_to_delete);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&guid_to_delete, guid, sizeof(guid)) == 0) {
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +				rv = fu_efivar_delete(guids, name, error);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &test);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&test, guid, sizeof(test)) == 0) {
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &test);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&test, guid, sizeof(test)) == 0) {
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> + * Since: 1.5.1
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> + * Copyright (C) 2021 Norbert Kamiński <norbert.kaminski@3mdeb.com>
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +static gchar *
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +	efi_str_to_guid(guids, &guid);
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (efi_get_variable_size (*guid, name, &size) < 0) {
Done.

2021-06-07 07:12 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +				if (!rv) {
Done.

2021-06-07 07:13 UTC, mkopec commented on libfwupdplugin/meson.build
> +if host_machine.system() == 'linux'
Done.

2021-06-07 07:13 UTC, mkopec commented on libfwupdplugin/fu-efivar-freebsd.c
> +		if (memcmp(&guid_to_delete, guid, sizeof(guid)) == 0) {
Done.

2021-06-07 08:07 UTC, closed without merging